"""
GRUB2 bootloader configuration and installation helpers.

Supports:
  - Legacy BIOS (i386-pc target)
  - UEFI  (x86_64-efi target)
  - Config generation with loopback ISO entries
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import textwrap
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Config file paths (relative to the mount-point / root of the USB drive)
# ---------------------------------------------------------------------------
GRUB_DIR = "boot/grub"
GRUB_CFG = f"{GRUB_DIR}/grub.cfg"
GRUB_THEME_DIR = f"{GRUB_DIR}/themes/nightmare"
ISO_DIR = "isos"
STATE_FILE = ".nightmare-loader.json"

# Source path of the bundled GRUB theme (inside this package)
_THEME_SRC = Path(__file__).parent / "theme" / "theme.txt"

# GRUB modules needed for both legacy and EFI targets
GRUB_MODULES = [
    "part_gpt",
    "part_msdos",
    "fat",
    "ntfs",
    "iso9660",
    "loopback",
    "linux",
    "chain",
    "normal",
    "configfile",
    "all_video",
    "gfxterm",
    "png",
    "echo",
    "cat",
    "reboot",
    "halt",
]

# ---------------------------------------------------------------------------
# GRUB config header builder
# ---------------------------------------------------------------------------

def _make_header(label: str = "NIGHTMARE") -> str:
    """
    Return the GRUB config header for a drive with the given volume label.

    The ``search`` command is critical: it tells GRUB to locate the USB drive
    by its FAT volume label so that ISO paths (e.g. /isos/ubuntu.iso) resolve
    correctly on any machine regardless of which USB port is used.
    Without it the loopback entries will not be found on first boot.

    The ``loadfont`` / gfxterm block is wrapped in an ``if`` so systems that
    lack the font file fall back gracefully to the text terminal.  The themed
    pre-loader (``set theme=``) is applied inside the same block so the
    Nightmare Loader splash appears before the boot menu is drawn.
    """
    return (
        "# Nightmare Loader – GRUB2 multi-ISO boot menu\n"
        "# Auto-generated – do not edit by hand; use nightmare-loader to manage ISOs.\n"
        "\n"
        "set default=0\n"
        "set timeout=10\n"
        "\n"
        "# Locate the USB drive by its volume label so ISO paths work on any\n"
        "# machine regardless of which port or slot the drive is plugged into.\n"
        f"search --no-floppy --label --set=root {label}\n"
        "\n"
        "insmod part_gpt\n"
        "insmod part_msdos\n"
        "insmod fat\n"
        "insmod iso9660\n"
        "insmod loopback\n"
        "insmod linux\n"
        "insmod all_video\n"
        "insmod gfxterm\n"
        "\n"
        "# Enable graphical terminal and Nightmare Loader theme if the font\n"
        "# is available; fall back silently to text mode otherwise.\n"
        "if loadfont ($root)/boot/grub/fonts/unicode.pf2; then\n"
        "    set gfxmode=auto\n"
        "    terminal_output gfxterm\n"
        "    set theme=($root)/boot/grub/themes/nightmare/theme.txt\n"
        "fi\n"
        "\n"
    )

_FOOTER = """
menuentry "Reboot" {
    reboot
}

menuentry "Power Off" {
    halt
}
"""


def install_grub_theme(mount_point: str | Path) -> Path:
    """
    Copy the bundled Nightmare Loader GRUB theme to the USB drive.

    The theme is installed to ``<mount_point>/boot/grub/themes/nightmare/``
    and is referenced automatically by the ``grub.cfg`` header generated by
    :func:`_make_header`.  The theme provides a dark, matrix-inspired splash
    before the boot menu appears: black background, green menu entries, and
    a red title / selection highlight that mirrors the web UI aesthetic.

    Parameters
    ----------
    mount_point:
        Root of the mounted USB partition.

    Returns
    -------
    Path
        Path to the written ``theme.txt`` on the USB drive.
    """
    theme_dir = Path(mount_point) / GRUB_THEME_DIR
    theme_dir.mkdir(parents=True, exist_ok=True)
    dest = theme_dir / "theme.txt"
    if _THEME_SRC.exists():
        shutil.copy2(str(_THEME_SRC), str(dest))
    return dest


def _linux_entry(label: str, isofile: str, kernel: str, initrd: str, cmdline: str) -> str:
    """Generate a single GRUB menuentry that loopback-mounts an ISO."""
    # isofile should be the path as seen by GRUB, e.g. /isos/ubuntu.iso
    filled_cmdline = cmdline.format(isofile=isofile)
    return textwrap.dedent(f"""\
        menuentry "{label}" {{
            set isofile="{isofile}"
            loopback loop "$isofile"
            linux (loop){kernel} {filled_cmdline}
            initrd (loop){initrd}
        }}
        """)


def _winpe_entry(label: str, isofile: str) -> str:
    """
    Generate a GRUB menuentry for a WinPE-based ISO (Hiren's BootCD PE, etc.).

    Uses EFI chain-boot: GRUB mounts the ISO via ``loopback`` and then hands
    off execution to the EFI binary inside the ISO.  This is the most reliable
    approach on modern UEFI systems (Windows 11 hardware).

    On legacy BIOS systems the chain-boot path is not available; the entry
    will fail gracefully with a GRUB error.  For BIOS support, ``wimboot``
    must be placed at ``/boot/grub/wimboot`` on the USB drive separately.
    """
    return textwrap.dedent(f"""\
        menuentry "{label} (UEFI)" {{
            set isofile="{isofile}"
            loopback loop "$isofile"
            chainloader (loop)/EFI/BOOT/BOOTX64.EFI
        }}
        """)



    """
    Generate a GRUB menuentry for a Windows ISO.

    Uses the ``ntldr`` / ``chainloader`` approach: we chain into the Windows
    boot manager after mapping the ISO as a virtual disk via the ``img_mount``
    command.  This requires the ``wimboot`` kernel to be installed alongside
    GRUB (copy wimboot to /boot/grub/wimboot on the USB stick).
    """
    return textwrap.dedent(f"""\
        menuentry "{label} (Windows – requires wimboot)" {{
            set isofile="{isofile}"
            loopback loop "$isofile"
            # Load wimboot to handle WIM-based Windows setup
            linux16 /boot/grub/wimboot
            initrd16 \
                newc:bootmgr:(loop)/bootmgr \
                newc:bcd:(loop)/Boot/BCD \
                newc:boot.sdi:(loop)/Boot/boot.sdi \
                newc:boot.wim:(loop)/sources/boot.wim
        }}
        """)


def generate_grub_cfg(entries: list[dict], label: str = "NIGHTMARE") -> str:
    """
    Generate a complete grub.cfg string from a list of ISO entry dicts.

    Each entry dict is the metadata dict produced by
    ``iso.get_iso_metadata``, enriched with an ``isofile`` key that holds
    the GRUB-side path to the ISO (e.g. ``/isos/ubuntu.iso``).

    Parameters
    ----------
    entries:
        List of entry dicts.  Expected keys: ``label``, ``isofile``,
        ``distro``, ``kernel``, ``initrd``, ``cmdline``.
    label:
        The FAT volume label of the drive.  Used in the ``search`` command
        so GRUB can locate the USB drive on first boot regardless of which
        port it is plugged into.  Must match the label used when the drive
        was formatted (default ``NIGHTMARE``).

    Returns
    -------
    str
        Full grub.cfg file content.
    """
    parts = [_make_header(label)]
    for entry in entries:
        distro = entry.get("distro", "generic")
        label = entry.get("label", entry.get("distro_label", entry.get("filename", "Unknown")))
        isofile = entry["isofile"]
        kernel = entry.get("kernel")
        initrd = entry.get("initrd")
        cmdline = entry.get("cmdline", "quiet splash")

        if distro == "windows" or (kernel is None and initrd is None):
            # Windows ISOs and any entry whose distro config has kernel=None /
            # initrd=None intentionally use the wimboot chain-boot path instead
            # of the standard linux/initrd loopback approach.
            parts.append(_windows_entry(label, isofile))
        else:
            parts.append(_linux_entry(label, isofile, kernel, initrd, cmdline))

    parts.append(_FOOTER)
    return "\n".join(parts)


def write_grub_cfg(mount_point: str | Path, entries: list[dict],
                   label: str = "NIGHTMARE") -> Path:
    """
    Write grub.cfg to ``<mount_point>/boot/grub/grub.cfg``.

    Parameters
    ----------
    mount_point:
        Root of the mounted USB drive.
    entries:
        ISO entries as returned by :func:`load_state`.
    label:
        FAT volume label of the drive.  Passed to :func:`generate_grub_cfg`
        so the ``search`` command in the header uses the correct label.

    Returns the path to the written file.
    """
    mount_point = Path(mount_point)
    cfg_path = mount_point / GRUB_CFG
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(generate_grub_cfg(entries, label=label))
    return cfg_path


def install_grub_bios(device: str, mount_point: str | Path) -> None:
    """
    Install GRUB2 for legacy BIOS boot onto *device*.

    Parameters
    ----------
    device:
        Block device path, e.g. ``/dev/sdb``.
    mount_point:
        Path where the device's main partition is mounted.
    """
    subprocess.run(
        [
            "grub-install",
            "--target=i386-pc",
            f"--boot-directory={Path(mount_point) / 'boot'}",
            "--recheck",
            device,
        ],
        check=True,
    )


def install_grub_efi(mount_point: str | Path, removable: bool = True) -> None:
    """
    Install GRUB2 for UEFI boot.

    Parameters
    ----------
    mount_point:
        Path where the EFI System Partition (ESP) is mounted (or the combined
        partition in the case of a hybrid USB).
    removable:
        If True, installs to the removable media fallback path
        (``EFI/BOOT/BOOTX64.EFI``), which is required for USB sticks that
        will be used on machines that don't have a persistent NVRAM entry.
    """
    cmd = [
        "grub-install",
        "--target=x86_64-efi",
        f"--efi-directory={mount_point}",
        f"--boot-directory={Path(mount_point) / 'boot'}",
        "--recheck",
    ]
    if removable:
        cmd.append("--removable")
    subprocess.run(cmd, check=True)


# ---------------------------------------------------------------------------
# State persistence (tracks which ISOs are registered on a drive)
# ---------------------------------------------------------------------------

def _state_path(mount_point: str | Path) -> Path:
    return Path(mount_point) / STATE_FILE


def load_state(mount_point: str | Path) -> dict:
    """Load the Nightmare Loader state JSON from the drive root."""
    path = _state_path(mount_point)
    if path.exists():
        return json.loads(path.read_text())
    return {"entries": []}


def save_state(mount_point: str | Path, state: dict) -> None:
    """Persist the Nightmare Loader state JSON to the drive root."""
    _state_path(mount_point).write_text(json.dumps(state, indent=2))
